name: Playwright Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - uses: microsoft/playwright-github-action@v1
      - name: Playwright
        run: |
          npm ci
          npm run test:e2e:playwright
        env:
          TEST_URL: ${{ secrets.TEST_URL }}
